name: Run Cardiovascular Notebook

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute modeling notebook
        run: |
          jupyter nbconvert --to notebook --execute notebooks/03_modeling_and_eval.ipynb \
            --output notebooks/03_modeling_and_eval_executed.ipynb \
            --ExecutePreprocessor.timeout=900
